---
title: "GeoMx_Tumor_Filtering"
output: html_document
date: "2024-01-25"
---

```{r setup, include=FALSE}
load("all_qc.RData")

library(NanoStringNCTools)
library(GeomxTools)
library(GeoMxWorkflows)
library(knitr)
library(dplyr)
library(ggforce)
library(readxl)
library(reshape2)
library(tidyverse)
library(pheatmap)
library(lmerTest)
library(reshape2)
library(cowplot)

pseudocount <- 1

log_adj <- function(x){
  return(log2(x + pseudocount))
}

calc_CV <- function(x) {sd(x) / mean(x)}
```

## Tumor Rich 
  
```{r Tumor_LOQ}
tumor_demoData <- target_demoData[, pData(target_demoData)$Comment == "Tumor-Rich" & pData(target_demoData)$Flag == "PASS"]
cutoff <- 2
minLOQ <- 2

# Calculate LOQ per module tested
LOQ <- data.frame(row.names = colnames(tumor_demoData))
for(module in modules) {
    vars <- paste0(c("NegGeoMean_", "NegGeoSD_"),
                   module)
    if(all(vars[1:2] %in% colnames(pData(tumor_demoData)))) {
        LOQ[, module] <-
            pmax(minLOQ,
                 pData(tumor_demoData)[, vars[1]] * 
                     pData(tumor_demoData)[, vars[2]] ^ cutoff)
    }
}
pData(tumor_demoData)$LOQ <- LOQ

LOQ_Mat <- c()
for(module in modules) {
    ind <- fData(tumor_demoData)$Module == module
    Mat_i <- t(esApply(tumor_demoData[ind, ], MARGIN = 1,
                       FUN = function(x) {
                           x > LOQ[, module]
                       }))
    LOQ_Mat <- rbind(LOQ_Mat, Mat_i)
}
# ensure ordering since this is stored outside of the geomxSet
LOQ_Mat <- LOQ_Mat[fData(tumor_demoData)$TargetName, ]
```

```{r Tumor_segment_filtering}
# Save detection rate information to pheno data
pData(tumor_demoData)$GenesDetected <- 
    colSums(LOQ_Mat, na.rm = TRUE)
pData(tumor_demoData)$GeneDetectionRate <-
    pData(tumor_demoData)$GenesDetected / nrow(tumor_demoData)

# Determine detection thresholds: 1%, 5%, 10%, 15%, >15%
pData(tumor_demoData)$DetectionThreshold <- 
    cut(pData(tumor_demoData)$GeneDetectionRate,
        breaks = c(0, 0.01, 0.05, 0.1, 0.15, 1),
        labels = c("<1%", "1-5%", "5-10%", "10-15%", ">15%"))

pData(tumor_demoData)
# stacked bar plot of different cut points (1%, 5%, 10%, 15%)
ggplot(pData(tumor_demoData),
       aes(x = DetectionThreshold)) +
    geom_bar(aes(fill = SITE)) +
    geom_text(stat = "count", aes(label = ..count..), vjust = -0.5) +
    theme_bw() +
    scale_y_continuous(expand = expansion(mult = c(0, 0.1))) +
    labs(x = "Gene Detection Rate",
         y = "Segments, #",
         fill = "Segment Type")

# ggsave("figs/strict-tumor-segment-detection-rate.png")

dplyr::count(pData(tumor_demoData), Comment, DetectionThreshold)
```

```{r Tumor_gene_filtering}
tdd <- tumor_demoData[, pData(tumor_demoData)$GeneDetectionRate >= 0.1 & pData(tumor_demoData)$Flag == "PASS"]
tdd <- tumor_demoData[, pData(tumor_demoData)$SITE != "PDX"]

# Calculate detection rate:
LOQ_Mat <- LOQ_Mat[, colnames(tdd)]
fData(tdd)$DetectedSegments <- rowSums(LOQ_Mat, na.rm = TRUE)
fData(tdd)$DetectionRate <-
    fData(tdd)$DetectedSegments / nrow(pData(tdd))

plot_detect <- data.frame(Freq = c(1, 5, 10, 20, 30, 50))
plot_detect$Number <-
    unlist(lapply(c(0.01, 0.05, 0.1, 0.2, 0.3, 0.5),
                  function(x) {sum(fData(tdd)$DetectionRate >= x)}))
plot_detect$Rate <- plot_detect$Number / nrow(fData(tdd))
rownames(plot_detect) <- plot_detect$Freq

ggplot(plot_detect, aes(x = as.factor(Freq), y = Rate, fill = Rate)) +
    geom_bar(stat = "identity") +
    geom_text(aes(label = formatC(Number, format = "d", big.mark = ",")),
              vjust = 1.6, color = "black", size = 4) +
    scale_fill_gradient2(low = "orange2", mid = "lightblue",
                         high = "dodgerblue3", midpoint = 0.65,
                         limits = c(0,1),
                         labels = scales::percent) +
    theme_bw() +
    scale_y_continuous(labels = scales::percent, limits = c(0,1),
                       expand = expansion(mult = c(0, 0))) +
    labs(x = "% of Segments",
         y = "Genes Detected, % of Panel > LOQ")

# ggsave("figs/strict-tumor-percent-segments-detected.png")

negativeProbefData <- subset(fData(tdd), CodeClass == "Negative")
neg_probes <- unique(negativeProbefData$TargetName)

tumor_demoData <- 
    tdd[fData(tdd)$DetectionRate >= 0.2 |
                        fData(tdd)$TargetName %in% neg_probes, ]

dim(tumor_demoData)
dplyr::count(pData(tumor_demoData), SAMPLE_ID)
```

```{r Tumor_Q3_norm}
# Graph Q3 value vs negGeoMean of Negatives
ann_of_interest <- "SITE"
Stat_data <- 
    data.frame(row.names = colnames(exprs(tumor_demoData)),
               Segment = colnames(exprs(tumor_demoData)),
               Annotation = pData(tumor_demoData)[, ann_of_interest],
               Q3 = unlist(apply(exprs(tumor_demoData), 2,
                                 quantile, 0.75, na.rm = TRUE)),
               NegProbe = exprs(tumor_demoData)[neg_probes, ])
Stat_data_m <- melt(Stat_data, measure.vars = c("Q3", "NegProbe"),
                    variable.name = "Statistic", value.name = "Value")

plt1 <- ggplot(Stat_data_m,
               aes(x = Value, fill = Statistic)) +
    geom_histogram(bins = 40) + theme_bw() +
    scale_x_continuous(trans = "log2") +
    facet_wrap(~Annotation, nrow = 1) + 
    scale_fill_brewer(palette = 3, type = "qual") +
    labs(x = "Counts", y = "Segments, #")

plt2 <- ggplot(Stat_data,
               aes(x = NegProbe, y = Q3, color = Annotation)) +
    geom_abline(intercept = 0, slope = 1, lty = "dashed", color = "darkgray") +
    geom_point() + guides(color = "none") + theme_bw() +
    scale_x_continuous(trans = "log2") + 
    scale_y_continuous(trans = "log2") +
    theme(aspect.ratio = 1) +
    labs(x = "Negative Probe GeoMean, Counts", y = "Q3 Value, Counts")

plt3 <- ggplot(Stat_data,
               aes(x = NegProbe, y = Q3 / NegProbe, color = Annotation)) +
    geom_hline(yintercept = 1, lty = "dashed", color = "darkgray") +
    geom_point() + theme_bw() +
    scale_x_continuous(trans = "log2") + 
    scale_y_continuous(trans = "log2") +
    theme(aspect.ratio = 1) +
    labs(x = "Negative Probe GeoMean, Counts", y = "Q3/NegProbe Value, Counts")

btm_row <- plot_grid(plt2, plt3, nrow = 1, labels = c("B", ""),
                     rel_widths = c(0.43,0.57))
plot_grid(plt1, btm_row, ncol = 1, labels = c("A", ""))

# remove outlier
tumor_demoData <- tumor_demoData[, !rownames(pData(tumor_demoData)) %in% c("DSP-1001660005648-A-C03.dcc")]

tumor_demoData <- normalize(tumor_demoData,
                             norm_method = "quant", 
                             desiredQuantile = .75,
                             toElt = "q_norm")

assayDataElement(object = tumor_demoData, elt = "log_q") <-
    assayDataApply(tumor_demoData, 2, FUN = log_adj, elt = "q_norm")

# png(file="figs/boxplot-raw-counts-tumor-rich.png", width=600, height=300)

boxplot(assayDataElement(tumor_demoData, elt="exprs"),
        col = "#9EDAE5", main = "Raw Counts",
        log="y", ylim = c(0.001, max(exprs(tumor_demoData))),
        ylab = "Counts", outline=FALSE, xaxt="n")
axis(side=1, tick=FALSE)

# dev.off()

# png(file="figs/boxplot-q3-norm-tumor-rich.png", width=600, height=300)

boxplot(assayDataElement(tumor_demoData, elt="q_norm"),
        col = "#2CA02C", main = "Q3 Norm Counts",
        log="y", ylim = c(0.001, max(assayDataElement(tumor_demoData, elt="q_norm"))),
        ylab = "Counts, Q3 Normalized", outline=FALSE, xaxt="n")
axis(side=1, tick=FALSE)

# dev.off()
# write.csv(assayDataElement(tumor_demoData, elt="exprs"), "tables/strict-tumor-raw-counts.csv")
# write.csv(assayDataElement(tumor_demoData, elt="q_norm"), "tables/strict-tumor-q3-normalized-counts.csv")
# write.csv(assayDataElement(tumor_demoData, elt="log_q"), "tables/strict-tumor-log-normalized-counts.csv")
# write.csv(subset(pData(tumor_demoData), select=-c(LOQ)), "tables/strict-tumor-metadata.csv")
```

```{r pam50}
library(genefu)
data(pam50.robust)


ddata <- t(exprs(tumor_demoData)) 
ddemo <- pData(tumor_demoData)
dannot <- fData(tumor_demoData) %>%
  dplyr::rename(EntrezGene.ID = GeneID) %>%
  dplyr::rename(probe = TargetName)
dannot[dannot$probe == 'ESR1',]

PAM50Preds<-intrinsic.cluster.predict(sbt.model=pam50, data=ddata,
                                         annot=dannot, do.mapping=TRUE,
                                         verbose=TRUE)

pData(tumor_demoData)$PAM50 <- PAM50Preds$subtype
# write.csv(subset(pData(tumor_demoData), select=-c(LOQ)), "tables/nopdx/tumor-metadata-pam50.csv")
```

```{r PCA_filtered_genes}
pcamat <- assayDataElement(tumor_demoData, elt="log_q")

# only to filter TNBC
# pData(tumor_demoData)[is.na(pData(tumor_demoData))] <- "None"
# tumor_tnbc <- tumor_demoData[, pData(tumor_demoData)$`Overall Subtype Primary` == "TNBC"]


# pcamat <- assayDataElement(pcamat, elt = "log_q")
# pcamat <- pcamat[ , colSums(is.na(pcamat))==0]
  
pca_cv <- apply(pcamat, 1, calc_CV)
pca_cv <- sort(pca_cv, decreasing = TRUE)
pca_goi <- names(pca_cv)[1:1000]

pc_out <- prcomp(t(pcamat[pca_goi,]), scale.=FALSE, center=TRUE)
pData(tumor_demoData)[, c("PC1", "PC2")] <- pc_out$x[,c("PC1", "PC2")]

# temp <- pData(tumor_demoData)
# sampleids <- temp$SAMPLE_ID
# sampleids <- gsub("_BR", "", sampleids)
# brs <- sampleids %in% c("BCBM_1", "BCBM_22", "BCBM_27")
# sampleids[!brs] <- "None"
# temp$MATCH <- sampleids

# dplyr::count(temp, SITE, MATCH)
             
ggplot(pData(tumor_demoData),
       aes(x = PC1, y = PC2, color=`PAM50`)) +
    geom_point(size = 2) +
    theme_bw() +
    xlab(paste("PC1 (", 100*summary(pc_out)[["importance"]][2,1], "%)", sep="")) +
    ylab(paste("PC2 (", 100*summary(pc_out)[["importance"]][2,2], "%)", sep="")) # +
    # scale_color_manual(values=c(None='grey', BCBM_1='purple', BCBM_22='green', BCBM_27='red'))

# ggsave("figs/nopdx/tumor-pca-by-pam50.png", height=15, width=15, unit="in")

# scree <- summary(pc_out)[["importance"]][2:3,]
# scree <- as.data.frame(t(scree))
# scree <- scree %>%
#   rownames_to_column(var="PC") %>%
#   mutate(PC = factor(PC, levels=PC)) %>%
#   rename(Proportion = `Proportion of Variance`, Cumulative = `Cumulative Proportion`)
# 
# ggplot(scree[1:10,]) + geom_col(aes(x=PC, y=Proportion, )) +
# geom_line(aes(x=PC, y=Cumulative), color='red', size=1, group=1) +
#       geom_point(aes(x=PC, y=Cumulative), color='red', size=3) + theme_bw()

# ggsave("figs/strict-tumor-scree-plot.png")
```
